### ISSUE TITLE
"wxid_xxx is not wxid, using weixin instead of wxid will potentially cause system failure."

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-padplus#103]
```
WARN This id: wxid_kwdsw9ngbnxr12 is not wxid, using weixin instead of wxid will potentially cause system failure. To make sure everything works as excepted, please use the wxid to load Contact. 
```

I'm keeping receiving the above error messages, which I can not understand at all.

BTW, Can we:

1. Make the error message be clearer, and
1. Add the module name to the error message, just like other parts of the Wechaty system?

**Comment by su-chang** [comment]
This warn is for `bot.Contact.load(id)`, when the id is not wxid and then will console warn log.

But it could not work right because we can not judge it by `Type7` attribute in low-level. So I will remove this log.

You mean we need to add `PRE` to log?

**Comment by huan** [comment]
The best practice to use `log.verbose` is:

```ts
log.verbose('ClassName', 'methodName() log messages ...')
```

It would be great if we can follow the above best practices in our Wechaty related modules.

Thanks.

**Comment by su-chang** [comment]
Agree, I will check all logs in padplus, and recorrect the bad one.

**Comment by huan** [comment]
Awesome, great to know that

**Comment by su-chang** [comment]
This issue has already been resolved, it will closed.
