### ISSUE TITLE
Unpredictable logout event  after error puppet-padplus

### ISSUE THREAD

**Issue by maxpaint** [wechaty/wechaty-puppet-padplus#107]
## 1. Versions

- What is your wechaty version?
Answer: "^0.29.8"

- What is your wechaty-puppet-padplus version?
Answer: "0.2.0"

- What is your node version? (run `node --version`)
Answer: node:10
- What OS are you using
Answer: docker image: node:10-slim

## 2. Describe the bug
Got an error from puppet (described below) and then puppet emitted logout event
## 3. To Reproduce
1. run puppet-padplus
2. login
3. send attachment
4. wait for 10 minutes

## 4. Expected behavior

puppet-padplus should stay logged in

## 5. Actual behavior

puppet-padplus receives an error (described below) and emits logout event

## 6. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
PADPLUS_ERROR EXIT 登录错误，请重新登录。 - Error: PADPLUS_ERROR EXIT 登录错误，请重新登录。
    at PuppetPadplus.puppet.on.error (/wechat-cluster/node_modules/wechaty/dist/src/wechaty.js:440:44)
    at PuppetPadplus.emit (events.js:198:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:448:20)
    at PuppetPadplus.emit (/wechat-cluster/node_modules/wechaty-puppet/dist/src/puppet.js:161:22)
    at PadplusManager.manager.on (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:86:22)
```

</details>

## 7. Additional context
We get this error from time to time. 

[bug]

**Comment by su-chang** [comment]
Thank you for your issue.

If the account has been logout by WeChat and then it will emit `error` event first to show the reason of logout, and then emit `logout` event.

It will optimize later, only `logout` event will emit in this case.

**Comment by maxpaint** [comment]
Restarting the server app or deploying the new version of the server app for wechaty-puppet-padplus can trigger this error?

**Comment by su-chang** [comment]
Nothing update about this issue, it will be closed.
