### ISSUE TITLE
Bot stops consume messages after ERR GRPC GATEWAY can not get a heartbeat from grpc server

### ISSUE THREAD

**Issue by maxpaint** [wechaty/wechaty-puppet-padplus#108]
## 1. Versions

- What is your wechaty version?
Answer: "^0.29.8"

- What is your wechaty-puppet-padplus version?
Answer: "0.2.0"

- What is your node version? (run `node --version`)
Answer: node:10
- What OS are you using
Answer: docker image: node:10-slim

## 2. Describe the bug
Bot stops consume messages after ERR GRPC GATEWAY can not get a heartbeat from grpc server

## 3. To Reproduce
1. run puppet-padplus
2. login
3. wait 
## 4. Expected behavior
Bot should successfully reconnect to the backend

## 5. Actual behavior
Lose connection with the backend
## 6. Full Output Logs
<details>
<summary>
Show Logs
</summary>

```shell
Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:
13:57:00 ERR GRPC_GATEWAY can not get heartbeat from grpc server
13:57:00 ERR GRPC_GATEWAY ApiType: 6 request timeout, traceId: f8b4596b-835e-49e1-bbc1-6b5dfbceafa0

```

</details>

[bug]

**Comment by su-chang** [comment]
Could you please let me know what the reason make the GRPC GATEWAY lost heartbeat? 

Disconnect the network or something that you think may be the answer. Thank you for your issue.

In normal case the bot will try to reconnect the server again and again until it success.

More logs are needed for this issue, so please append your logs here and maybe we could find something in the logs.

**Comment by maxpaint** [comment]
Restarting the server app or deploying the new version of the server app for wechaty-puppet-padplus can trigger this error?

**Comment by su-chang** [comment]
Could you please show me the detail logs if you need my help.

**Comment by maxpaint** [comment]
Our code just listening to the errors from the Bot and write the error to log and 
the example of code
```shell
const bot = botFactory.createBot(token, userId);
bot.on("error", onError);
function onError(error) {
    log.error(error);
}
```
As I understand the Bot sends to us only the error message without the addition information

**Comment by su-chang** [comment]
```js
BROLOG_LEVEL=silly node index.js
```
This command will help you to get some detail logs.

**Comment by su-chang** [comment]
Nothing update about this issue, it will be closed now.
