### ISSUE TITLE
PuppetPadplus not a class derived from 'Puppet'.

### ISSUE THREAD

**Issue by quantumFlame** [wechaty/wechaty-puppet-padplus#142]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```
No

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:
"wechaty": "^0.31.3"

- What is your wechaty-puppet-padplus version?
Answer:  "wechaty-puppet-padplus": "^0.3.26"

- What is your node version? (run `node --version`)
Answer:  v11.14.0

- What os are you using
Answer: Ubuntu 16.04 

## 2. Describe the bug

Give a clear and concise description of what the bug is.
Error message: 'PuppetPadplus' is not a class derived from 'Puppet'

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. follow the example in readme
```
mkdir my-padplus-bot && cd my-padplus-bot
npm init -y
tsc --init
npm install wechaty@next
npm install wechaty-puppet-padplus@next
npm install qrcode-terminal
```

2. create test.ts
```ts
import { Wechaty       } from 'wechaty'
import { PuppetPadplus } from 'wechaty-puppet-padplus'
import QrcodeTerminal from 'qrcode-terminal'

const token = 'your-token'

const puppet = new PuppetPadplus({
  token,
})

const name  = 'your-bot-name'

const bot = new Wechaty({
  puppet,
  name, // generate xxxx.memory-card.json and save login data for the next login
})

bot
  .on('scan', (qrcode, status) => {
    QrcodeTerminal.generate(qrcode, {
      small: true
    })
  })
  .on('message', msg => {
    console.log(`msg : ${msg}`)
  })
  .start()
```

3. ts-node test.ts

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.
No error reported

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.
Error message returned.

![image](https://user-images.githubusercontent.com/5970757/74119906-3bd10680-4b76-11ea-9684-c0afb4e7d575.png)

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

# WECHATY_
LOG=silly ts-node test.ts 
/usr/lib/node_modules/ts-node/src/index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
test.ts:14:3 - error TS2322: Type 'PuppetPadplus' is not assignable to type '"wechaty-puppet-mock" | "wech
aty-puppet-padplus" | "wechaty-puppet-puppeteer" | "wechaty-puppet-wechat4u" | Puppet'.
  Type 'PuppetPadplus' is not assignable to type 'Puppet'.
    Property 'options' is protected but type 'PuppetPadplus' is not a class derived from 'Puppet'.
14   puppet,
     ~~~~~~
  node_modules/wechaty/dist/src/wechaty.d.ts:31:5
    31     puppet?: PuppetModuleName | Puppet;
           ~~~~~~
    The expected type comes from property 'puppet' which is declared here on type 'WechatyOptions'
    at createTSError (/usr/lib/node_modules/ts-node/src/index.ts:421:12)
    at reportTSError (/usr/lib/node_modules/ts-node/src/index.ts:425:19)
    at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:530:36)
    at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:735:32)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:814:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts
:817:12)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)

```

</details>

## 7. Additional context

[bug]

**Comment by huan** [comment]
Quick answer: replace your wechat version from `@next` to `@latest` will fix your issue.

Replace v0.31 to v0.30 in your case.

**Comment by huan** [comment]
If you do want to use `wechaty@next`, please make sure you have the required technics to solve the problems that you might run into.

## Solution 2

With `wechaty@0.31`, you can make your code work by changing code to declare your puppet by name, and let Wechaty helps you to manage it, with the following code:

```ts
const token  = 'your-token'
const puppet = 'wechaty-puppet-padplus'
const name   = 'your-bot-name'

const bot = new Wechaty({
  name,
  puppet,
  puppetOptions: { token },
})
```

**Comment by huan** [comment]
Please remember that we should always use the @latest version of an NPM module. If you want to use the `@next` version, please make sure you have the required technics to solve the problems that you might run into.

Learn more from our FAQ about the Semantic Versioning, and the difference between @next and @latest:
https://github.com/wechaty/wechaty/wiki/FAQ#3-how-to-understand-the-wechaty-semantic-versioning
