### ISSUE TITLE
FlashStore 会写满磁盘的问题

### ISSUE THREAD

**Issue by wenh7788** [wechaty/wechaty-puppet-padplus#155]
挂的微信号联系人（通讯录）有421人
微信号所在的群大概有100多个，每个群的群成员平均有200多个
我们的服务器的硬盘是10G，运行一段时间我们的服务器会报警，写满磁盘

**Comment by su-chang** [comment]
Thanks for your issue, we will fix this bug in next latest version.

**Comment by huan** [comment]
A workaround code for FlashStore@0.18:

```ts
async function compact (store: FlashStore): Promise<void> {
  await store.size
  const db = (store as any).levelDb.db.db.db
  await new Promise((resolve, reject) => {
    db.compact((err: any) => {
      if (err) {
        return reject(err)
      }
      resolve()
    })
  })
}
```

Run `compact(store)` on a FlashStore instance to runs a compaction process on the database files. 
 Reduces the size of data on disk. Deletes old log entries.
