### ISSUE TITLE
DUPLICATE CONNECTED, THIS THREAD WILL EXIT NOW

### ISSUE THREAD

**Issue by shianqi** [wechaty/wechaty-puppet-padplus#169]
I tried to deploy my code in a different environment, but the process in the production environment keeps restarting. What causes ["DUPLICATE CONNECTED, THIS THREAD WILL EXIT NOW"](https://github.com/wechaty/wechaty-puppet-padplus/blob/92d20aff75af3dde12496e31345e657f1bebcaef/src/server-manager/grpc-gateway.ts#L407)?

**Comment by su-chang** [comment]
Thanks for your issue.

`DUPLICATE CONNECTED, THIS THREAD WILL EXIT NOW`

It means that we could only keep one token with one WeChat account.

So if we meet this warning log, please checkout whether you start wechaty bot in different process or environment.

**Comment by moderncrazy** [comment]
The error is reported at 9:00 this morning. No other application is using this token.

```
09:05:14 INFO GRPC_GATEWAY 
        =====================================================================
                   DUPLICATE CONNECTED, THIS THREAD WILL EXIT NOW
        =====================================================================
        See: https://github.com/wechaty/wechaty-puppet-padplus/issues/169
```

The prompt error after local debugging appears here: [can not find callback by traceId](https://github.com/wechaty/wechaty-puppet-padplus/blob/92d20aff75af3dde12496e31345e657f1bebcaef/src/server-manager/grpc-gateway.ts#L469)
