### ISSUE TITLE
install wechaty-puppet-padplus failed

### ISSUE THREAD

**Issue by yee-lab** [wechaty/wechaty-puppet-padplus#172]
$ npm i wechaty-puppet-padplus

> fs-ext@2.0.0 install C:\Users\Hu\Desktop\WechatBot\node_modules\fs-ext
> node-gyp configure build

C:\Users\Hu\Desktop\WechatBot\node_modules\fs-ext>if not defined npm_config_node_gyp (node "C:\DevTools\nvm\v10.19.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "C:\DevTools\nvm\v10.19.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\DevTools\nvm\v10.19.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at findVisualStudio2013 (C:\DevTools\nvm\v10.19.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16)
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\DevTools\nvm\v10.19.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at findVisualStudio2015 (C:\DevTools\nvm\v10.19.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14)
gyp ERR! stack     at regSearchKeys (C:\DevTools\nvm\v10.19.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16)
gyp ERR! stack     at regGetValue (C:\DevTools\nvm\v10.19.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7)
gyp ERR! stack     at C:\DevTools\nvm\v10.19.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\DevTools\\nodejs\\node.exe" "C:\\DevTools\\nvm\\v10.19.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\Hu\Desktop\WechatBot\node_modules\fs-ext
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN WechatBot@1.0.0 No description
npm WARN WechatBot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fs-ext@2.0.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fs-ext@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hu\AppData\Roaming\npm-cache\_logs\2020-03-03T19_47

**Comment by yee-lab** [comment]
1. Start PowerShell as Administrator and run:
       `npm install --global windows-build-tools`
2. `npm install -g node-gyp`
   Next execution `npm install --save wechaty-puppet-padplus`

**Comment by su-chang** [comment]
Thanks for your answer. 

It would help a lots of developer when install `wechaty-puppet-padplus` in Windows.
