### ISSUE TITLE
room-event-join-message-parser can't parser  sysmsg type NewXmlDisableChatRoomAccessVerifyApplication

### ISSUE THREAD

**Issue by yangshizi** [wechaty/wechaty-puppet-padplus#176]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer: 0.31.26

- What is your wechaty-puppet-padplus version?
Answer: 0.4.6

- What is your node version? (run `node --version`)
Answer: v12.14.1

- What os are you using
Answer: mac os

## 2. Describe the bug

Give a clear and concise description of what the bug is.

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node bot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:
Error: unknown jsonPayload sysmsg type: NewXmlDisableChatRoomAccessVerifyApplication
    at Object.<anonymous> (/Users/cooter/Projects/node.js/bot/node_modules/_wechaty-puppet-padplus@0.4.6@wechaty-puppet-padplus/dist/src/pure-function-helpers/room-event-join-message-parser.js:105:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/cooter/Projects/node.js/bot/node_modules/_wechaty-puppet-padplus@0.4.6@wechaty-puppet-padplus/dist/src/pure-function-helpers/room-event-join-message-parser.js:5:58)
(node:26973) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: NewXmlDisableChatRoomAccessVerifyApplication
    at Object.<anonymous> (/Users/cooter/Projects/node.js/bot/node_modules/_wechaty-puppet-padplus@0.4.6@wechaty-puppet-padplus/dist/src/pure-function-helpers/room-event-join-message-parser.js:105:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/cooter/Projects/node.js/bot/node_modules/_wechaty-puppet-padplus@0.4.6@wechaty-puppet-padplus/dist/src/pure-function-helpers/room-event-join-message-parser.js:5:58)
(node:26973) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8789)
```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Please provide the reproduce steps, then we will fix the bug as quick as possible.

**Comment by su-chang** [comment]
@yangshizi could you provide the reproduce step for this issue? Or describe the trigger operation of this case?

**Comment by su-chang** [comment]
This issue will be resolved in the next version.

**Comment by su-chang** [comment]
Already resolved, please update these dependencies:
`npm install wechaty@latest`
`npm install wechaty-puppet-padplus@latest`
