### ISSUE TITLE
puppetPadplus.start() should return after it finish all the start tasks.

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-padplus#189]
I found in some conditions that the `puppetPadplus.start()` will not resolve for a long time, e.g. 3 minutes (maybe longer because I did not wait for it anymore).

### The Problem

If the `puppetPadplus.start()` can not return properly (properly means that it should return a `Promise` that resolved after it finished the `start()` procedures as soon as possible), it will block all the Wechaty framework initializations, which will lead to unknown problems.

From the current version of Wechaty source code of the `start()` method:

https://github.com/wechaty/wechaty/blob/2f1b8a3721915cf54be38369102b64f4cbe6f557/src/wechaty.ts#L848-L882

We can see that if the `await this.puppet.start()` will not be resolved, then the `heartbeat` and `start` event will never be fired.

https://github.com/wechaty/wechaty/blob/2f1b8a3721915cf54be38369102b64f4cbe6f557/src/wechaty.ts#L874-L881

**Comment by huan** [comment]
I believe I found the reproduce steps for this problem.

The PR will demonstrate how to block the whole system from here:

https://github.com/wechaty/wechaty-puppet-padplus/blob/7f548ee2aa61c21d775c018b3dcffd7dfae29b1f/src/padplus-manager/padplus-manager.ts#L236

**Comment by huan** [comment]
Could we take a look at this bug this week? Because it's a blocking issue for puppet management.

**Comment by su-chang** [comment]
OK, I will fix it later. Thank you very much for provided the reproduce steps.

**Comment by huan** [comment]
Did we have fixed this issue, or do we have any updates form this problem?

**Comment by su-chang** [comment]
> await this.padplusUser.initInstance()

This promise method has been resolved, and will not hanging any more.

**Comment by huan** [comment]
Great to know that, thank you very much for the update!

**Comment by su-chang** [comment]
The server has already updated and this problem been fixed, and this issue will be closed now.
