### ISSUE TITLE
ERR PuppetPadplus messageRawPayload([object Object]) manager.cacheManager.getMessage([object Object]) return nothing

### ISSUE THREAD

**Issue by yo-huge** [wechaty/wechaty-puppet-padplus#192]
## 1. Versions

- What is your wechaty version?
Answer:"0.32.5"

- What is your wechaty-puppet-padplus version?
Answer:"0.5.25"

- What is your node version? (run `node --version`)
Answer:v10.15.3

- What os are you using
Answer:macos

## 2. Describe the bug

When start a simple demo and receive a message, then report the error.
But last Friday, it is normal.

And I find that the scan event has modify the arguments, the first arguments is a object, not string, but the document has not modify
```
import {Wechaty} from 'wechaty'
import QrcodeTerminal from 'qrcode-terminal'

const bot = Wechaty.instance()

bot
.on('scan', ({qrcode, status}) => {
    QrcodeTerminal.generate(qrcode, {
      small: true
    })
})

.on('login', user=>{
    console.log(`${user} login`)
})

.on('message', msg => {
    console.log(`msg : ${msg}`)
})

.start()
```

```
11:00:26 ERR PuppetPadplus messageRawPayload([object Object]) manager.cacheManager.getMessage([object Object]) return nothing.
(node:43929) UnhandledPromiseRejectionWarning: Error: no message rawPayload for message id [object Object]
    at PuppetPadplus.<anonymous> (/Users/huyi/Documents/mine/webot/node_modules/wechaty/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:1162:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/huyi/Documents/mine/webot/node_modules/wechaty/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
```

## 3. To Reproduce

1. run 'WECHATY_PUPPET=wechaty-puppet-padplus node start.js'

**Comment by su-chang** [comment]
> Error: no message rawPayload for message id [object Object]

Could you provide more context logs about this error?

**Comment by peterpan0708** [comment]
same error, can anyone handle this?

**Comment by su-chang** [comment]
Workaround: 
`npm i wechaty@0.35.5`

**Comment by Matear890** [comment]
What is your wechaty version?
Answer:"0.31.26"

What is your wechaty-puppet-padplus version?
Answer:"0.5.29"

What is your node version? (run node --version)
Answer:v12.2.0

What os are you using
Answer:CentOS7

log:

`11:09:24 INFO storeName: message-raw-payload 
11:09:24 INFO storeName: friendship-raw-payload 
11:09:24 INFO storeName: room-invitation-payload 
11:09:28 ERR PuppetPadplus messageRawPayload([object Object]) manager.cacheManager.getMessage([object Object]) return nothing.
(node:25323) UnhandledPromiseRejectionWarning: Error: no message rawPayload for message id [object Object]
    at PuppetPadplus.<anonymous> (/wechaty_robot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:1075:23)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty_robot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
(node:25323) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:25323) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
11:09:30 ERR PuppetPadplus messageRawPayload([object Object]) manager.cacheManager.getMessage([object Object]) return nothing.
(node:25323) UnhandledPromiseRejectionWarning: Error: no message rawPayload for message id [object Object]
    at PuppetPadplus.<anonymous> (/wechaty_robot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:1075:23)
    at Generator.next (<anonymous>)`
