### ISSUE TITLE
Is there a way to run a on-premise gRPC endpoint server?

### ISSUE THREAD

**Issue by Alan-Liang** [wechaty/wechaty-puppet-padplus#198]
<https://github.com/wechaty/wechaty-puppet-padplus/blob/7274e52be9e061f0741bbbed2499a25e780eb088/src/config.ts#L55>
I meant that can I deploy my own server like the one on `padplus.juzibot.com:50051`? Since we refuse to use [SaaSS](https://www.gnu.org/philosophy/who-does-that-server-really-serve.html) and this repo looks like a wrapper around the gRPC API, we would like to confirm that we could have the gRPC server running on our own servers.

**Comment by su-chang** [comment]
This repo is wrapper around the gRPC API.

Sorry to say that the gRPC server is a private server.

**Comment by Alan-Liang** [comment]
Alright...
