### ISSUE TITLE
Puppet Agnostic Pad Scripting

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-puppet-padplus#210]
**Is your feature request related to a problem? Please describe.**

Wechaty framework actually has the power to change the puppet on the fly:

```
WECHATY_PUPPET=wechaty-puppet-mock node starter-bot.js
WECHATY_PUPPET=wechaty-puppet-puppeteer node starter-bot.js
```

I.e., the same script, `starter-bot.js`, does not need to specify which puppet it is using, all can be provided at run time from command line. 

However, [`wechaty-puppet-padplus` based client code](https://github.com/wechaty/wechaty-puppet-padplus#example) is not there yet.

**Describe the solution you'd like**

I'll see if I can try to make starter-bot.js to be puppet agnostic, so `wechaty-puppet-padplus` based script can be started with the same ideology as well. 

If I make it, I'll report back. 

[enhancement]

**Comment by suntong** [comment]
Working now. 

Tested with **wechaty-getting-started** `examples/ding-dong-bot.js`. 
See https://github.com/wechaty/wechaty-getting-started/issues/106 & https://github.com/wechaty/wechaty-getting-started/issues/107.

**Comment by su-chang** [comment]
It seems that no problem with this issue, it will be closed now. Thanks for your effort to Wechaty!
