### ISSUE TITLE
Fix the default bug reporting template

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-puppet-padplus#211]
In the the default bug reporting template, it says:

```
## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

npm install wechaty-puppet-padlus@next
```

I.e. it is asking everyone to use `wechaty-puppet-padlus@next`, the **@next** version, before reporting any bugs. 

However, one person [did so](https://github.com/wechaty/wechaty-puppet-padplus/issues/142), but it brings more trouble than it solves. [As per @huan]()https://github.com/wechaty/wechaty-puppet-padplus/issues/142#issuecomment-583947829:

> Please remember that we should always use the @latest version of an NPM module. If you want to use the `@next` version, please make sure you have the required technics to solve the problems that you might run into.

So I think the default bug reporting template should use `@latest` instead of `@next`, and I'll report my next bug in such a way.

**Comment by su-chang** [comment]
Thanks for pointing out this problem.

This is a special case due to we have reverted one dependence package which require node version `v10` in `wechaty-puppet-padplus@next`. When we revert back, all things will work as it expected.

**Comment by suntong** [comment]
Ah, got you. 
K. I'll close this.
