### ISSUE TITLE
method start got blocked. 

### ISSUE THREAD

**Issue by JesseWeb** [wechaty/wechaty-puppet-padplus#216]
## 1. Versions
- What is your wechaty version?
Answer: ^0.38.4

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:padplus

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:^0.6.1

- What is your node version? (run `node --version`)
Answer:10.15.3

- What os are you using
Answer:macOS Catalina 10.15.4

## 2. Describe the bug and reproduce
wechaty instance method `start` got  blocked!
## 3. To Reproduce
```
 (
async function(){
const wechaty = Wechaty.instance({
         name: WECHATY_NAME,
         puppet: 'wechaty-puppet-padplus',
         puppetOptions: {
            token: PUPPET_PAD_PLUS_TOKEN
         }
      })
await wechaty.start()
console.log(`bot just get online`)
...other stuff here
})()
```

## 4. Expected behavior

terminal will print `bot just get online`
## 5. Actual behavior

none of has been printed.

## 6. Additional context
in fact. the process are stuck at `await wechaty.start()`

but in the documentation. it says 
```
await bot.start()
// do other stuff with bot here
// All the bot operation needs to be triggered after start() is done
```
i am confused!!! am i doing the wrong way?

[bug]

**Comment by JesseWeb** [comment]
one question.  
are these lifecycles(down below) consistent?

if is not then what's the different between these two.

#### 1、
```
bot.start().then(()=>{
    //context
})
```
#### 2、
```
bot.on("login",()=>{
  //context
})
```

**Comment by su-chang** [comment]
`bot.on(event, callback)`
listener on event

`bot.start()`
start the bot

**Comment by JesseWeb** [comment]
> `bot.on(event, callback)`
> listener on event
> 
> `bot.start()`
> start the bot

is start method resolved after it initialized contains first `login` event?

**Comment by huan** [comment]
No, there's no guarantee of any order to be consistent.

It is heavily depends on the puppet implantation.

**Comment by su-chang** [comment]
@JesseWeb  The server has already updated, please check this issue again, if there's no problem about it, please close it. Thank you very much.

**Comment by JesseWeb** [comment]
@su-chang Aye-Aye, Captain!
