### ISSUE TITLE
The message.toUrlLink is not a function

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-puppet-padplus#218]
## 1. Versions

```
$ node -v
v10.20.0

$ npm ls wechaty wechaty-puppet wechaty-puppet-mock wechaty-puppet-puppeteer wechaty-puppet-padplus
wechaty-getting-started@0.1.20 /.../nodejs/wechaty-examples
├─┬ wechaty@0.38.4 
│ └── wechaty-puppet@0.24.0  deduped
├── wechaty-puppet@0.24.0 
├── wechaty-puppet-mock@0.20.4 
├── wechaty-puppet-puppeteer@0.18.6 
└── wechaty-puppet-padplus@0.6.1 

```

- What os are you using

```
$ lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
## 2. Describe the bug

It seams that the padplus puppet that I'm using doesn't support such function.

## 3. To Reproduce

The [wechaty doc says](https://docs.chatie.io/api/message#message-tourllink-promise-less-than-urllink-greater-than) 

> `message.toUrlLink()` ⇒ Promise `<UrlLink>`
Get Url Link of the Message Extract the Url Link from the Message, and encapsulate it into UrlLink class

So say I get such link via `const link = await message.toUrlLink()`, then how can I deal with it? I tried:

      console.log(link)

but I'm getting the following:

    (node:1672) UnhandledPromiseRejectionWarning: TypeError: message.toUrlLink is not a function
        at Wechaty.onMessage (/.../on-message.js:219:32)
    (node:1672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)

Does it mean that the padplus puppet that I'm using doesn't support such function? 

[bug]

**Comment by su-chang** [comment]
The answer is that `wechaty-puppet-padplus` support `toUrlLink()`. 

If you want to know some detail info, please see: https://github.com/wechaty/wechaty-puppet-padplus/blob/master/src/puppet-padplus.ts#L728

Could you please provide more detail logs for this issue? And please make sure the `message` is type of `Message`.

**Comment by suntong** [comment]
Indeed, something wrong with my own code then. thanks for the swift reply.
