### ISSUE TITLE
在ready事件后获取  以及ready事件数据全部加载完成后的每一次心跳事件获取所有群都会固定缺失

### ISSUE THREAD

**Issue by windy-gf** [wechaty/wechaty-puppet-padplus#222]

**Comment by su-chang** [comment]
Could you provide some detail info about what you want to description?

I guess that your problem is that the bot can not load all rooms at once? Right or not?

The bot will load active room or room which has been added in Contact List when each start.

**Comment by su-chang** [comment]
Nothing update about this issue, it will be closed now.
