### ISSUE TITLE
The bot always logout

### ISSUE THREAD

**Issue by lightlizm** [wechaty/wechaty-puppet-padplus#223]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:^0.38.4

- What is your wechaty-puppet-padplus version?
Answer:^0.6.2

- What is your node version? (run `node --version`)
Answer:v10.15.0

- What os are you using
Answer: win7

## 2. Describe the bug

The bot always  logout  about every one  hour .

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run 'node index.js' 

## 4. Expected behavior

Keep the bot online 

## 5. Actual behavior

The bot always logout

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
16:30:09 **ERR GRPC_GATEWAY can not get heartbeat from grpc server**
(node:14140) UnhandledPromiseRejectionWarning: Error: can not send message due to this error: Error: can not get response from grpc server
    at PadplusMessage.<anonymous> (D:\amp\nodejs\node_modules\wechaty-puppet-padplus\dist\src\padplus-manager\api-request\message.js:180:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\amp\nodejs\node_modules\wechaty-puppet-padplus\dist\src\padplus-manager\api-request\message.js:5:58)
(node:14140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:14140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
16:30:17 WARN Puppet constructor() watchdog.on(reset) reason: {"data":"f2239418-c6b5-4526-8b67-ccbaeff1b4bb","timeout":60000}
16:30:17 INFO PuppetPadplus stop()
16:30:17 INFO PuppetPadplus logout(true, logout in wechaty)
None JingDong Promotion
16:30:22 INFO PuppetPadplus start()
16:30:24 INFO GRPC_GATEWAY
        =====================================================================
                   DUPLICATE CONNECTED, THIS THREAD WILL EXIT NOW
        =====================================================================
        See: https://github.com/wechaty/wechaty-puppet-padplus/issues/169
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]
![errorlog](https://user-images.githubusercontent.com/40618556/79632866-9ef1a180-8194-11ea-8c77-e6276f5aebb9.png)

**Comment by su-chang** [comment]
Could you provide some reproduce step for this issue? I think it's really helpful for resolve problem.
