### ISSUE TITLE
公众号 图文 消息Onmessage监测

### ISSUE THREAD

**Issue by guoxiangke** [wechaty/wechaty-puppet-padplus#224]
功能需求：指定公众号消息的第X条消息转发到指定群里
Hi，现在测试可以监测到bot发送的消息到公众号
但是公众号的响应信息（包括文本和图文链接）都无法监测。

![2020-04-23_06-27-24 (1)](https://user-images.githubusercontent.com/1160703/80040166-12e0d080-852c-11ea-9d02-69a5b499a8c3.gif)

而且公众号响应的音频，转发都会提示：不支持的消息类型，希望能够支持。
![image](https://user-images.githubusercontent.com/1160703/80040446-ae724100-852c-11ea-8ff2-5524b857e0fc.png)

**Comment by su-chang** [comment]
Sorry to say that `wechaty-puppet-padplus` can not support receive OA message.

**Comment by guoxiangke** [comment]
https://github.com/wechaty/wechaty/issues/1938

**Comment by su-chang** [comment]
@guoxiangke Hi, I think `wechaty-puppet-donut` could help you, this puppet is based on Windows WeChat hook, it could send and receive OA message, but now it is in alpha test phase.

More detail, see: https://github.com/wechaty/wechaty/issues/1941
