### ISSUE TITLE
无法发送图片

### ISSUE THREAD

**Issue by CI2VO5IXZ7** [wechaty/wechaty-puppet-padplus#228]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:
0.38.4
- What is your wechaty-puppet-padplus version?
Answer:
0.7.13
- What is your node version? (run `node --version`)
Answer:
12.13.1
- What os are you using
Answer:
windows&centos
## 2. Describe the bug
参照https://github.com/wechaty/wechaty-getting-started/blob/master/examples/advanced/media-file-bot.js和https://github.com/wechaty/wechaty-getting-started/blob/master/examples/ding-dong-bot.js。
#########################################################################
 let n = msg.type()
    if (n == 6) {
      const file =await msg.toFileBox()
      const name = file.name
      console.log('Save file to: ' + name)
      file.toFile(name)
      const room = await bot.Room.find({id: "1234567890@chatroom" })
      room.say(file)
    }
#########################################################################
无法转发图片。主要是会卡在room.say(file)。使用msg.forward(room)同样不行。
## 3. To Reproduce
报错信息如下：
ERR GRPC_GATEWAY ApiType: SEND_FILE request timeout, traceId: b529e725-2578-428a-8a4d-5b518c39cc93
(node:752) UnhandledPromiseRejectionWarning: Error: can not get callback result of SEND_FILE, subType : pic
    at PadplusMessage.<anonymous> (C:\Users\lnb24\WebstormProjects\wechaty\node_modules\wechaty-puppet-padplus\dist\src\padplus-manager\api-request\message.js:144:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\lnb24\WebstormProjects\wechaty\node_modules\wechaty-puppet-padplus\dist\src\padplus-manager\api-request\message.js:5:58)
(node:752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
All received Image message can not forward to other Contact or Room?

Could you please have a test for some other images?

BTW, what the interval time between each forward?

**Comment by CI2VO5IXZ7** [comment]
> All received Image message can not forward to other Contact or Room?
> Yes,All.I have tested many times. I can't send or forward image to room. Contact didn't test.

> Could you please have a test for some other images?
> 
> BTW, what the interval time between each forward?
> Sorry,I didn't understand what you mean. I didn't set the interval time.

**Comment by su-chang** [comment]
```js
if (message.type() === MessageType.Image) {
  const fileBox = await message.toFileBox()
  await fileBox.toFile()
  await message.forward(message.from())
}
```
Try this code again, and print your log below, if problem still existed.

**Comment by CI2VO5IXZ7** [comment]
Here is my code:
`
module.exports = bot => {
  return async function onMessage(msg) {
    if (msg.self()) return
    if (msg.age() > 60) return
    if (msg.type() == 6) {
      const fileBox = await msg.toFileBox()
      await fileBox.toFile()
      await msg.forward(msg.from())
    }
  }
}
`
Here is the Log:
13:17:55 ERR GRPC_GATEWAY ApiType: SEND_FILE request timeout, traceId: fceecda3-d208-4a23-b913-e4c5530d69bf
13:17:55 ERR Message forward(Contact<CI2VO5IXZ7>) exception: Error: can not get callback result of SEND_FILE, subType : pic
(node:41648) UnhandledPromiseRejectionWarning: Error: can not get callback result of SEND_FILE, subType : pic
    at PadplusMessage.<anonymous> (C:\Users\lnb24\WebstormProjects\wechaty\node_modules\wechaty-puppet-padplus\dist\src\padplus-manager\api-request\message.js:144:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\lnb24\WebstormProjects\wechaty\node_modules\wechaty-puppet-padplus\dist\src\padplus-manager\api-request\message.js:5:58)
(node:41648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:41648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by su-chang** [comment]
I have reproduce this problem, we will fix it sooner.

Thanks for your issue.

**Comment by su-chang** [comment]
This problem will be fixed after `v0.7.15`.

You can upgrade your `wechaty-puppet-padplus`, and check it again, if no problem any more, please close this issue, thank you very much.

**Comment by CI2VO5IXZ7** [comment]
你好，我刚测试了下，是可以转发图片的，但是如果我选则了发送原图，转发出来的图片部分会强制转成横向图片。附图是我发送的几张图片及转发的情况。
![10ca5415838f2a79592e136a2271685](https://user-images.githubusercontent.com/38647090/80268031-f0d78180-86d6-11ea-9af9-4bce4992763a.jpg)
![43409fa56186b03ac08decc67b7ea97](https://user-images.githubusercontent.com/38647090/80268032-f2a14500-86d6-11ea-907d-72bae615e6c7.jpg)

**Comment by su-chang** [comment]
```js
const image = message.toImage()
const fileBox = await image.artwork()
await contact.say(fileBox)
```

For the full image, you can try this way.

BTW, please keep the topic of this issue pure. Maybe this problem need a new issue.
