### ISSUE TITLE
IO error

### ISSUE THREAD

**Issue by chenyx1934** [wechaty/wechaty-puppet-padplus#229]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:^0.38.4

- What is your wechaty-puppet-padplus version?
Answer:^0.7.14

- What is your node version? (run `node --version`)
Answer:v10.15.3

- What os are you using
Answer:windows

## 2. Describe the bug
扫码登陆确认后报错
![image](https://user-images.githubusercontent.com/12790656/80172600-050c7780-8620-11ea-864d-c1b8a81706e4.png)

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
11:37:16 INFO PuppetPadplus start()
brolog.js:183
OpenError: IO error: Failed to create dir: C:\Users\陈远新\.wechaty\puppet-padplus-cache\flash-store-v0.14\king-yun\message-raw-payload: No such file or directory
    at D:\Eguan\prepare\wechaty-getting-started\node_modules\_levelup@4.4.0@levelup\lib\levelup.js:119:23
    at D:\Eguan\prepare\wechaty-getting-started\node_modules\_abstract-leveldown@6.2.3@abstract-leveldown\abstract-leveldown.js:38:14
    at D:\Eguan\prepare\wechaty-getting-started\node_modules\_deferred-leveldown@5.3.0@deferred-leveldown\deferred-leveldown.js:31:21
    at D:\Eguan\prepare\wechaty-getting-started\node_modules\_abstract-leveldown@6.3.0@abstract-leveldown\abstract-leveldown.js:38:14
    at D:\Eguan\prepare\wechaty-getting-started\node_modules\_abstract-leveldown@6.1.1@abstract-leveldown\abstract-leveldown.js:30:14
c
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Could you please try remove node_modules and package-lock.json, and install them again?

```
rm -rf node_modules package-lock.json
npm install
```

**Comment by chenyx1934** [comment]
> Could you please try to remove node_modules and package-lock.json, and install them again?
> 
> ```
> rm -rf node_modules package-lock.json
> npm install
> ```

Tried, but it didn't work

**Comment by su-chang** [comment]
Could you please have a try to create folder, like that `C:\Users\陈远新\.wechaty\puppet-padplus-cache\flash-store-v0.14\king-yun`?

**Comment by chenyx1934** [comment]
> Could you please have a try to create folder, like that `C:\Users\陈远新\.wechaty\puppet-padplus-cache\flash-store-v0.14\king-yun`?
The folder exists
![image](https://user-images.githubusercontent.com/12790656/80173319-0048c300-8622-11ea-84af-f3634122e198.png)

**Comment by su-chang** [comment]
OK, please check your bot process, does it not close in other node process?

BTW, `restart` can not resolved this problem?

**Comment by chenyx1934** [comment]
It didn't work

**Comment by su-chang** [comment]
Any progress on this issue?

**Comment by JesseWeb** [comment]
Not familiar with windows platform. 
You might wanna try these 2 opts. 
1. Create a folder without Chinese path as your project root. Run `non cache clean —force` Then try again. 
2. Open terminal with administrator. Delete `node_modules` `package-lock.json`. Run `non cache clean —force` and try again.

**Comment by chenyx1934** [comment]
The problem is that the file path has Chinese characters. It seems that the path stores user data and is the default. I wonder if it can be defined as a configurable path. My project code location does not have Chinese characters

**Comment by su-chang** [comment]
You can create a `feature issue` to `wechaty-puppet-padplus` for what you want.

@JesseWeb @chenyx1934 Thank you very much, I will close this issue now.
