### ISSUE TITLE
你的微信登录环境存在异常。为了帐号安全，本次登录已失效

### ISSUE THREAD

**Issue by guoxiangke** [wechaty/wechaty-puppet-padplus#231]
docker 运行在腾讯云服务器上，运行一个定时任务 半小时执行一次（*/30 * * * *），其实定时发送任务失败（代码问题），今早发现日志这么写的：

> app_1  | 19:05:23 INFO PuppetPadplus logout(true, 你的微信登录环境存在异常。为了帐号安全，本次登录已失效。)
> app_1  | 19:05:23 INFO StarterBot Contact<AI机器人> logout

有封号风险吗，或者需要养号吗？

**Comment by ax4** [comment]
理论上来说没有封号的风险，触发这个可能更类似于被flag了一下然后暂时踢出了这次登陆的session，重新登陆/升级客户端/换一个客户端，可能都可以解决这个问题。目前来说还没有因为跳这个警告之后被封号的case出现。

**Comment by guoxiangke** [comment]
问题重现：

> let path="http://www.xxx.com/1.mp3" // URL 正常可访问
> let answer = FileBox.fromUrl(encodeURI(path))
> return receiver.say(answer)

出错日志：
```
05:35:00 ERR GRPC_GATEWAY ApiType: 50 request timeout, traceId: b9457ffc-6453-439a-828f-8826a5f621fc
05:35:00 ERR Config ###########################
05:35:00 ERR Config unhandledRejection: Error: can not get callback result of SEND_FILE, subType : doc [object Promise]
05:35:00 ERR Config ###########################
05:35:00 ERR Config process.on(unhandledRejection) promise.catch(can not get callback result of SEND_FILE, subType : doc)
Config Error: can not get callback result of SEND_FILE, subType : doc
    at PadplusMessage.<anonymous> (/Users/xx/Code/juzibot/GCED/node_modules/wechaty-puppet-padplus/src/padplus-manager/api-request/message.ts:146:15)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xx/Code/juzibot/GCED/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/message.js:5:58)
(node:82258) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
05:35:09 VERB PuppetPadplus logout(你的微信登录环境存在异常。为了帐号安全，本次登录已失效。)
```

**Comment by su-chang** [comment]
> 为啥会显示文件类型 doc呢？ subType : doc

In the server side, we regard `.mp3` as `doc` file, it is not the key point for this issue.

Do you set the `name` for your `Wechaty`? If it is your first time to login `Wechaty` by this account, it's a normal case, and then if you set `name` this warning message wont be shown any more.

**Important** `name` could help your WeChat account keep the session for the server.
