### ISSUE TITLE
群接龙 消息 监测

### ISSUE THREAD

**Issue by guoxiangke** [wechaty/wechaty-puppet-padplus#232]
app_1  | 22:07:41 INFO Message#Unknown[🗣Contact<楊X>@👥Room<xxx小组>]	<?xml version="1.0"?>
app_1  | <msg>
app_1  | 	<appmsg appid="" sdkver="0">
app_1  | 		<title>#接龙

**Comment by su-chang** [comment]
It is support after `v0.7.14`.

BTW, you should upgrade your `wechaty@next` too.
