### ISSUE TITLE
请教下  linux 下安装失败

### ISSUE THREAD

**Issue by beclass** [wechaty/wechaty-puppet-padplus#233]
![image](https://user-images.githubusercontent.com/12541388/80310832-42832780-880f-11ea-9550-6486042ecd6a.png)
![image](https://user-images.githubusercontent.com/12541388/80310867-6e061200-880f-11ea-8f84-bc5443dc648b.png)

**Comment by guoxiangke** [comment]
apt-get install g++ 
and others

**Comment by beclass** [comment]
还是不行 💔
![image](https://user-images.githubusercontent.com/12541388/80343827-2d52db00-8899-11ea-8e5a-529a7166f334.png)

**Comment by su-chang** [comment]
Could you please have a look at https://github.com/wechaty/wechaty-puppet-padplus/blob/master/readme.md , and do what the `readme` suggestion.

If still some problem existed, please show more info about it.

Thank you very much.

**Comment by beclass** [comment]
ok，CentOs下是安装gcc-c++

**Comment by su-chang** [comment]
Could you run a `Node.js` program success or not in your linux system?

BTW, please keep your node version to `10.16.0`.

**Comment by su-chang** [comment]
@beclass Anything update about this issue?
