### ISSUE TITLE
为何要放弃在grpc客户端做长链的方案

### ISSUE THREAD

**Issue by moremorefun** [wechaty/wechaty-puppet-padplus#238]
在之前的`wechaty-puppet-padpro`项目中采用的是客户端做长链，然后将二进制数据发送给服务端验证的方案。这种做法的好处是客户端的IP作为长链IP，避免需要在grpc服务器提供多个IP的需求。

请问为何要放弃这种方案，或者是否有继续维护`wechaty-puppet-padpro`的想法？

**Comment by su-chang** [comment]
Simple answer: No

Long answer: Due to the different basic protocal, we have to change the connect way of grpc. And sorry to say that `wechaty-puppet-padpro` will not work anymore.
