### ISSUE TITLE
群名防串改时，每次都报错 Error: get room timeout

### ISSUE THREAD

**Issue by guoxiangke** [wechaty/wechaty-puppet-padplus#240]
代码 15 16行
 
![image](https://user-images.githubusercontent.com/1160703/82136422-95fdf980-9840-11ea-8432-a62620fab683.png)

报错
```
(node:83113) UnhandledPromiseRejectionWarning: Error: get room timeout
    at Timeout._onTimeout (/Users/dale/Code/juzibot/GCED/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:1259:47)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:83113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 57)

13:12:36 WARN Room topic(newTopic=主人042) exception: get room timeout
```

**Comment by su-chang** [comment]
Could you please provide more detail log about this issue?

**Two Questions**

1. Does the method `room.say('请勿随意更改群名', changer)` success or not?
2. Could you please make sure this log `get room timeout` is correspond to the room in `onRoomTopic`?

**Comment by guoxiangke** [comment]
> Could you please provide more detail log about this issue?
> 
> **Two Questions**
> 
> 1. Does the method `room.say('请勿随意更改群名', changer)` success or not?
> 2. Could you please make sure this log `get room timeout` is correspond to the room in `onRoomTopic`?

1. yes, it's success
2. yes, I am sure the log is generate by this action.(test many times) 

but it works without the timeout error now. 
thanks for your time.
