### ISSUE TITLE
接收公众号消息

### ISSUE THREAD

**Issue by UnsignedInt8** [wechaty/wechaty-puppet-padplus#242]
当公众号向用户发送消息时，请问padplus并没有处理该类消息吗？或许这是个bug？

**Comment by su-chang** [comment]
Sorry, it is not supported.

**Comment by UnsignedInt8** [comment]
> Sorry, it is not supported.

That's fine

**Comment by lijiarui** [comment]
@UnsignedInt8 you can try wechaty-puppet-donut. That puppet can support this, and you can apply alpha test token here: https://github.com/wechaty/wechaty/issues/1941
