### ISSUE TITLE
In production: Contact.weixin() sometimes gives null where Contact comes from msg.from() in onMessage for some newly added people

### ISSUE THREAD

**Issue by archywillhe** [wechaty/wechaty-puppet-padplus#277]
## 1. Versions
- What is your wechaty version?
Answer: 0.40.8

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: padplus

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: 0.7.18

- What is your node version? (run `node --version`)
Answer: 13.9.0

- What os are you using
Answer: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-48-generic x86_64)

## 2. Describe the bug

`.weixin()` sometimes return null. Maybe cuz `.payload.weixin` is null or `payload` not loaded at all. Super werid. 

Still trying to replicate this bug.

(Maybe it's cuz when adding the person there was a network issue and something wasn't initalised properly? )

**Comment by su-chang** [comment]
Could you please make sure `contact.id` is look like `wxid_xxxxx` when the `weixin()` return null.

BTW, it better to show more detail info in this issue.

**Comment by archywillhe** [comment]
@su-chang thanks for attending this issue! Yeah I'm still testing to see what cases it will return `null`. Will get back with more info in a bit!

**Comment by archywillhe** [comment]
haven't been able to replicate similiar issue; closing.

**Comment by su-chang** [comment]
Thank you for your response.
