### ISSUE TITLE
版本升机后@人功能失效

### ISSUE THREAD

**Issue by usersuccess** [wechaty/wechaty-puppet-padplus#292]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:
^0.40.10
- What is your wechaty-puppet-padplus version?
Answer:
^0.7.36
- What is your node version? (run `node --version`)
Answer:
v10.15.0
- What os are you using
Answer:
部分代码如下:
 //获取需要@的人
                                        for (let i = 0; i < arr.length; i++)
                                        {
                                            let meb:any = await bot.Contact.find({alias:arr[i]});
                                            userInfo[i]=meb
                                        }
                                        console.log(userInfo);
                                        sleep(2000);
                                        await contact.say(content_echo,...userInfo)
## 2. Describe the bug
服用历史代码,可获取到对应的人，但是@人无效
Give a clear and concise description of what the bug is.

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
We can not reproduce this problem, could you please provide more info about it?

BTW, a simple example for you:
```
await room.say('test mention somebody', message.from())
```

Please check it work or not, maybe it would help you to find out the exactly problem.

Thank you.
