### ISSUE TITLE
onMessage can't receive the message sent by puppet 

### ISSUE THREAD

**Issue by treeguard** [wechaty/wechaty-puppet-padplus#302]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer: wechaty@0.40.10

- What is your wechaty-puppet-padplus version?
Answer: wechaty-puppet-padplus@0.7.36

- What is your node version? (run `node --version`)
Answer: v13.12.0

- What os are you using
Answer: Mac & Linux

## 2. Describe the bug

I used the puppet to send a miniProgram to a room, however, I didn't see the message on the onMessage handler. Besides, I didn't see the issue on donut. 

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Please see: https://github.com/wechaty/wechaty-puppet-padplus#how-to-emit-the-message-that-you-sent

**Comment by treeguard** [comment]
@su-chang thanks for the pointer!
