### ISSUE TITLE
how to get Multi-shares?

### ISSUE THREAD

**Issue by zxypetre** [wechaty/wechaty-puppet-padplus#312]
![webwxgetmsgimg](https://user-images.githubusercontent.com/31026087/94108458-ee3dab80-fe71-11ea-9a28-15110250916d.jpeg)
类似这种有两篇文章的分析，使用msg..toUrlLink() 只能获取第一篇文章信息，有办法获取下面的信息吗？

**Comment by su-chang** [comment]
Sorry, it's not supported now.

**Comment by zxypetre** [comment]
![image](https://user-images.githubusercontent.com/31026087/94223286-24d2ff00-ff22-11ea-9898-7a9a8e4aba8a.png)
Thank you for your reply，I got the required information through msg.text
