### ISSUE TITLE
[FriendShip][Add] No result accidental happen when add friend.

### ISSUE THREAD

**Issue by CooperFu** [wechaty/wechaty-puppet-padplus#33]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
0.28.3
- What is your wechaty-puppet-padplus version?
0.0.114

- What is your node version? (run `node --version`)
v10.16.0

- What os are you using
linux

## 2. Describe the bug

No result accidental happen when add friend.

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

bot.friendShip.add('13237170888')

```
41|wechaty | 2019-09-23 18:21 +08:00: start--------------- 13237170888
41|wechaty | 2019-09-23 18:22 +08:00: err------- Error: can not get callback result
41|wechaty | 2019-09-23 18:22 +08:00:     at PadplusContact.<anonymous> (/home/deploy/wechaty_padplus/source/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/contact.js:48:23)
41|wechaty | 2019-09-23 18:22 +08:00:     at Generator.next (<anonymous>)
41|wechaty | 2019-09-23 18:22 +08:00:     at fulfilled (/home/deploy/wechaty_padplus/source/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/contact.js:5:58)
```

bot.friendShip.add('13701617719')

```
41|wechaty | 2019-09-23 18:30 +08:00: start--------------- 13701617719
41|wechaty | 2019-09-23 18:30 +08:00: end--------------- {"avatar":"http://wx.qlogo.cn/mmhead/ver_1/3FrAP21XvHlSEbxzCq85ibYEbZrxIty1c6aLXSFtg2ER6rR3MvOTG4xKlVviaicZ4picia3zDvib2oicRWBmBKOjvoKrKHxX0wSPy0u6QGX1LKAmjc/132","v1":"v1_09e8e631a311d0c3cb55ded33200fe291f97e8ecf1dce29b86745428996e9081@stranger","v2":"v2_71995488b296116496a5f1efa5f118fc0d44e1978b9927b10c1fc0fec95a0877210409cabad50899274074704b883f28@stranger","searchId":"13701617719","nickName":"琳琳²⁰¹⁹","wxid":"qq1739819895","message":"Everything is OK","status":"0"}
```

But '13237170888' phone number is actual `searchable` in my wechat. it`s very strange.

[bug]

**Comment by su-chang** [comment]
This issue will be closed as it is no longer active.
