### ISSUE TITLE
call logout() failed, cannot trigger wechat logout from phone

### ISSUE THREAD

**Issue by aslanTT** [wechaty/wechaty-puppet-padplus#40]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 1. Versions

- What is your wechaty version?
Answer:

0.28.3

- What is your wechaty-puppet-padplus version?
Answer:

0.0.123

- What is your node version? (run `node --version`)
Answer:

v10.16.0

- What os are you using
Answer:

linux

## 2. Describe the bug

OpenError: IO error: lock /Users/aslan/.wechaty/puppet-padplus-cache/flash-store-v0.14/wxid_4zibvi2z4zxh32/accound-wxid/LOCK: No locks available
    at /Users/aslan/Work/padchat/node_modules/levelup/lib/levelup.js:119:23
    at /Users/aslan/Work/padchat/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
    at /Users/aslan/Work/padchat/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /Users/aslan/Work/padchat/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
    at /Users/aslan/Work/padchat/node_modules/rocksdb/node_modules/abstract-leveldown/abstract-leveldown.js:41:14

## 3. To Reproduce

call logout function

**Comment by su-chang** [comment]
Sorry this function has not supported now.

**Comment by su-chang** [comment]
Already resolved.

Please update `wechaty-puppet-padplus@latest`
