### ISSUE TITLE
can not use room.qrcode()

### ISSUE THREAD

**Issue by makk24** [wechaty/wechaty-puppet-padplus#42]
message:"Method not implemented."
stack:"Error: Method not implemented.\n    at PuppetPadplus.roomQrcode (e:\project\gitPro\wxpro\wechat-pad\node_modules\wechaty-puppet-padplus\dist\src\puppet-padplus.js:866:15)\n    at AnotherOriginalClass.<anonymous> (e:\project\gitPro\wxpro\wechat-pad\node_modules\wechaty\dist\src\user\room.js:748:46)\n    at Generator.next (<anonymous>)\n    at e:\project\gitPro\wxpro\wechat-pad\node_modules\wechaty\dist\src\user\room.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (e:\project\gitPro\wxpro\wechat-pad\node_modules\wechaty\dist\src\user\room.js:3:12)\n    at AnotherOriginalClass.qrcode (e:\project\gitPro\wxpro\wechat-pad\node_modules\wechaty\dist\src\user\room.js:746:16)\n    at e:\project\gitPro\wxpro\wechat-pad\index.js:414:29\n    at process._tickCallback (internal/process/next_tick.js:68:7)"

**Comment by su-chang** [comment]
Sorry for that.

The method `room.qrcode()` is not supported by Padplus now.
