### ISSUE TITLE
【Room】can not create room by member

### ISSUE THREAD

**Issue by scholar-wei** [wechaty/wechaty-puppet-padplus#43]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:0.29.2

- What is your wechaty-puppet-padplus version?
Answer:0.0.126

- What is your node version? (run `node --version`)
Answer:v10.15.3

- What os are you using
Answer:mac

## 2. Describe the bug

群创建失败

## 3. To Reproduce

 const ContactB = await bot.Contact.find({name: '源'});
                const ContactA = await bot.Contact.find({name: '替身'});
                const contactList = [ContactA, ContactB];

                // console.log('Bot', 'contactList: %s', contactList.join(','));
                const room = await bot.Room.create(contactList, '替身创建群');
                await room.sync();
                await room.topic('替身创建群');
                await room.say('替身创建群');
## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
14:25:17 VERB Room create(Contact<替身>,Contact<源>, 替身创建群)
brolog.js:190
14:25:17 SILL PUPPET_PADPLUS topic : 替身创建群, contactIdList: iyunxiao6465,wxid_hrm3rhgapdkg22
brolog.js:190
14:25:17 SILL PadplusManager careteRoom : 替身创建群, iyunxiao6465,wxid_hrm3rhgapdkg22
brolog.js:190
14:25:17 VERB PadplusRoom createRoom(替身创建群,memberIdsiyunxiao6465,wxid_hrm3rhgapdkg22)
brolog.js:190
14:25:17 SILL REQUEST request()
brolog.js:190
14:25:17 SILL GRPC_GATEWAY GRPC Request ApiType: 32
brolog.js:190
14:25:17 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S== 
brolog.js:190
14:25:17 SILL GRPC_GATEWAY responseType: 0, data : {"roomId":"","status":0,"createMessage":[{"wxid":"iyunxiao6465","status":1},{"wxid":"wxid_hrm3rhgapdkg22","status":6}],"message":""}
brolog.js:190
14:25:17 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
 
brolog.js:190
14:25:17 ERR Room create() exception: Error: can not create room by member: [{"wxid":"iyunxiao6465","status":1},{"wxid":"wxid_hrm3rhgapdkg22","status":6}]
</summary>

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Is this issue still existed? Can you create room successfully with these contacts in WeChat App?

**Comment by su-chang** [comment]
Nothing update about this issue, it will be closed.
