### ISSUE TITLE
Session is not terminated after bot.logout() and bot.stop() are called

### ISSUE THREAD

**Issue by andriipustovoit** [wechaty/wechaty-puppet-padplus#73]
## 1. Versions

- What is your wechaty version?
    "wechaty": "^0.29.5",

- What is your wechaty-puppet-padplus version?
    "wechaty-puppet-padplus": "0.0.146",

- What is your node version? (run `node --version`)
Answer: v11.6.0

- What os are you using
Answer: Ubuntu

## 2. Describe the bug

After the bot is not needed we try to terminate the session by calling the code:

    bot.logout().catch(e => log.error(e)).finally(() => {
      bot.stop().catch(e => log.error(e)).finally(() => {
          process.exit(0)
        );
      })
    });

## 4. Expected behavior

The session on iPad is terminated

## 5. Actual behavior

The memory-card file still is present on filesystem and on phone WeChat application there is "Logged in to WeChat for iPad" bar visible

## 6. Full Output Logs

no errors are displayed except one info message:

INFO Wechaty <Puppet#0<PuppetPadplus>(/....../wechat-cluster/memory-card/c5a0c25d-41d1-40ce-bdf2-b0d8a9a87415)> stop() v0.29.7 is stoping ...

Library versions:
    "wechaty": "^0.29.5",
    "wechaty-puppet": "^0.17.2",
    "wechaty-puppet-padplus": "0.0.146",
    "memory-card": "0.6.21"

**Comment by su-chang** [comment]
Sorry, the method `logout` can not support to logout the WeChat App.

**Comment by su-chang** [comment]
Already supported.

Please update `wechaty-puppet-padplus@latest`
