### ISSUE TITLE
Puppet, phone and desktop application don't work together

### ISSUE THREAD

**Issue by maxpaint** [wechaty/wechaty-puppet-padplus#78]
## 1. Versions

- What is your wechaty version?
Answer: "wechaty": "^0.29.5",

- What is your wechaty-puppet-padplus version?
Answer: "wechaty-puppet-padplus": "0.0.146"

- What is your node version? (run `node --version`)
Answer: v11.6.0

- What os are you using
Answer: Ubuntu

## 2. Describe the bug

User is logged out from puppet after login in desktop application

## 3. To Reproduce
1) User logins to Wechat in  smartphone
2) User logins to puppet
3) User logins to desktop application

## 4. Expected behavior
User logged to Wecha in on 3 devices  

## 5. Actual behavior
The user is logged out from the puppet. 

## 6. Full Output Logs
not require 

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
This is not a problem with `puppet`, it's due to WeChat App, it only supported two devices to login, and one must be `phone`, the other one which you could choose is that `desktop application` or `puppet` or `iPad` and so on. So `puppet` login, `desktop application` logout.

**Comment by maxpaint** [comment]
Thanks!
