### ISSUE TITLE
update how to install in README 

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty-puppet-padplus#83]
Readme shows how to install here:

> 2. Install the latest wechaty
> npm install wechaty@next
> 3. Install wechaty-puppet-padplus
> Notice: wechaty-puppet-padplus still in alpha test period, so we keep updating the package, you should install the latest packge by using @latest until we release the stable package.
> npm install wechaty-puppet-padplus@latest

Why we install next and latest version here? If padplus is stable now, I suggest we change this to :

```
npm install wechaty
```

and 
```
npm install wechaty-puppet-padplus
```

**Comment by su-chang** [comment]
```js
npm install wechaty
```
It will install `wechaty@latest` by default, but some new features are depends on `wechaty@next`.

Padplus is stable now, we will publish `padplus@latest` start with 0.2.0 version and `padplus@next` start with 0.3.0 version in this week.

And then we will change this readme to:
```js
npm install wechaty@next
```
and
```js
npm install wechaty-puppet-padplus
```

**Comment by lijiarui** [comment]
If padplus is stable version, we should always change to 

```
npm i wechaty
```
and 
```
npm i wechaty-puppet-padplus
```

If we add `next` here, it may make developers confuse about this.

**Comment by su-chang** [comment]
We can not run wechaty with wechaty-puppet-padplus success by both version are @latest.

wechaty@latest == wechaty@0.28.3 

This version has not added padplus to puppet npm module.

> This commit in wechaty@0.29.3 has add padplus to config  https://github.com/wechaty/wechaty/commit/c2e554e4a45f355b21a500c985b62176974bfb22

Maybe wechaty should publish latest version 0.29.3.

**Comment by su-chang** [comment]
Already resolved.
