### ISSUE TITLE
这个项目是需要付费使用的， 还是免费使用的？是需要购买TOKEN吗

### ISSUE THREAD

**Issue by qrcent** [wechaty/wechaty-puppet-padplus#94]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by su-chang** [comment]
We have declared that in this [doc](https://github.com/wechaty/wechaty-puppet-padplus/blob/master/readme.md).

> We provide a free token for the developers who have a strong will and ability to build a valuable chatbot for users.
> 
> Any developers can send info following the template to dev@juzi.bot
> 
> See more: https://github.com/wechaty/wechaty/wiki/Support-Developers
